
config wifi-device 'mt7603e'
	option type 'mt7603e'
	option vendor 'ralink'
	option channel '0'
	option bw '0'
	option autoch '2'
	option radio '1'
	option hwband '2_4G'
	option hwmode '11ng'
	option disabled '0'
	option region '1'
	option aregion '6'
	option txbf '3'
	option txpwr 'max'
	option country 'RU'

config wifi-iface
	option device 'mt7603e'
	option ifname 'wl1'
	option network 'lan'
	option mode 'ap'
	option disabled '0'
	option ssid 'Xiaomi_7492'
	option encryption 'mixed-psk'
	option hidden '0'
	option bsd '0'
	option rrm '0'
	option wnm '0'

config wifi-iface 'minet_ready'
	option disabled '1'
	option device 'mt7603e'
	option ifname 'wl2'
	option network 'ready'
	option mode 'ap'
	option ssid 'minet_ready'
	option hidden '1'
	option encryption 'none'

config wifi-iface 'guest_2G'
	option disabled '1'
	option device 'mt7603e'
	option ifname 'wl3'
	option network 'guest'
	option mode 'ap'

config wifi-iface 'miot_2G'
	option device 'mt7603e'
	option ifname 'wl4'
	option network 'miot'
	option mode 'ap'
	option ssid '25c829b1922d3123_miwifi'
	option disabled '0'
	option encryption 'none'
	option wmm '1'
	option hidden '1'
	option vifidx '3'
	option bindstatus '0'
	option userswitch '1'

config wifi-device 'mt7663'
	option type 'mt7663'
	option vendor 'ralink'
	option channel '0'
	option bw '0'
	option autoch '2'
	option radio '1'
	option hwband '5G'
	option hwmode '11ac'
	option disabled '0'
	option region '1'
	option aregion '6'
	option txbf '3'
	option txpwr 'max'
	option country 'RU'

config wifi-iface
	option device 'mt7663'
	option ifname 'wl0'
	option network 'lan'
	option mode 'ap'
	option disabled '0'
	option encryption 'mixed-psk'
	option hidden '0'
	option bsd '0'
	option rrm '0'
	option wnm '0'
	option ssid 'Xiaomi_7492_5G'

